export enum NotificationType {
  PROJECT_INVITATION = 'PROJECT_INVITATION',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  COMMENT_MENTION = 'COMMENT_MENTION',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
}
